### PR TITLE
Add iOS build

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by pasin** [comment]
Should it use archive instead of build to get the bitcode?

**Comment by borrrden** [comment]
@pasin How do we currently verify if bitcode is included?  I saw a post saying thet `otool -l | grep __LLVM` was the way, but I see those entries in my static library even though I didn't archive.

**Comment by borrrden** [comment]
I managed to find the difference.  Here is the library built with the default settings (examining the armv7 slice):

> sectname __bitcode
   segname __LLVM
      addr 0x000723c0
      size 0x00000001
    offset 469620
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0

Notice the size of 1 (Just a marker, as a result of `-fembed-bitcode-marker`)

If I modify the project to not emit the marker, and add `-fembed-bitcode` myself I get this:

> sectname __bitcode
   segname __LLVM
      addr 0x00072340
      size 0x0048a030
    offset 469492
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0

Now the size is 4.7596 megabytes.  Repeat that again and the library is almost 10MB larger (sigh).  @hideki Do you want me to just update the build script and lib directly on master?

**Comment by pasin** [comment]
The most accurate way to check if the bitcode is really included is to archive an app that uses the binary. It should work if you add -fembed-bitcode.

**Pull request merged**
